// <auto-generated />
using System;
using CaseLEKSTIASPNETMVCSimplificado.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CaseLEKSTIASPNETMVCSimplificado.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230108002854_Add-Migration Movimentations")]
    partial class AddMigrationMovimentations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CaseLEKSTIASPNETMVCSimplificado.Models.Commodity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MovimentationsId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberRecord")
                        .HasColumnType("int");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MovimentationsId");

                    b.ToTable("Commodities");
                });

            modelBuilder.Entity("CaseLEKSTIASPNETMVCSimplificado.Models.Movimentations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("EntryOrExitEnum")
                        .HasColumnType("int");

                    b.Property<string>("Local")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Movimentations");
                });

            modelBuilder.Entity("CaseLEKSTIASPNETMVCSimplificado.Models.Commodity", b =>
                {
                    b.HasOne("CaseLEKSTIASPNETMVCSimplificado.Models.Movimentations", null)
                        .WithMany("commodity")
                        .HasForeignKey("MovimentationsId");
                });

            modelBuilder.Entity("CaseLEKSTIASPNETMVCSimplificado.Models.Movimentations", b =>
                {
                    b.Navigation("commodity");
                });
#pragma warning restore 612, 618
        }
    }
}
